name: Deploy

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "{{ secrets.TOKEN_SECRECT }}"

      - name: Print message
        run: echo "This is the first job"
      
      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: '18'
